GoogleCloudPlatform/public-datasets-pipelines

- CONTRIBUTORS
- datasets/ml_datasets/_terraform/ml_datasets_dataset.tf
- datasets/ml_datasets/_terraform/penguins_pipeline.tf
- datasets/ml_datasets/_terraform/provider.tf
- datasets/ml_datasets/_terraform/variables.tf
- datasets/ml_datasets/dataset.yaml
- datasets/ml_datasets/penguins/penguins_dag.py
- datasets/ml_datasets/penguins/pipeline.yaml
Adding this dataset to create a BQ AutoML Tabular tutorial.
> Added penguins DAG

- README.md
> fix: Add missing link to YAML config reference in repo README

- renovate.json
Based on #34. Automatically get up-to-date with package versions using renovate bot.
> feat: add renovate bot

- OWNERS
> chore: Add leahecole as a code reviewer and approver

- .github/PULL_REQUEST_TEMPLATE.md
Updates the pull request template with a note on editing the items based on what's applicable for the PR at hand.
I also removed items from the checklist that are already covered by the automated checks, i.e. "Linters pass" and "Tests pass".
> docs: Updated pull request template

- README.md
Adds Python as a requirement (with specific version range) and adds a missing `>=` for Airflow versions in the README.
> docs: Added Python and Airflow version requirements

- renovate.json
> fix: Fixed renovate config

- datasets/vaccination_access/vaccination_access_to_bq/pipeline.yaml
chore: Add more operators for each csv file.
> chore: Update pipeline.yaml with more operators

- README.md
Switch from Public Datasets Program to Datasets for Google Cloud.
> chore: Use Datasets for Google Cloud link

- CONTRIBUTORS
> chore: adds goog-pegman as a contributor

- README.md
> docs: Added missing link to `pipeline.yaml` sample

- README.md
> docs: prepend `pipenv run` to the Python commands

- datasets/google_dei/_terraform/diversity_annual_report_pipeline.tf
- datasets/google_dei/_terraform/google_dei_dataset.tf
- datasets/google_dei/dataset.yaml
- datasets/google_dei/diversity_annual_report/pipeline.yaml
- Revised `google_dei` dataset description to include meaning of DEI acronym
- Fixes escaped quotes for the `dar_*` tables
> fix: Minor revisions to DAR dataset and table descriptions

- header-checker-lint.yml
> feat: Adds Google license header bot config

- README.md
> docs: Add best practices for percentage data and hierarchies

- README.md
Changed from `airflow initdb` (Airflow 1) to `airflow db init` (Airflow 2)
> docs: Revised Airflow DB initialization command

- .gitignore
Ignores JSON files created during prototyping.
> chore: Ignore nested JSON files under `datasets`

- datasets/san_francisco_trees/_images/run_csv_transform_kub/Dockerfile
- datasets/san_francisco_trees/_images/run_csv_transform_kub/csv_transform.py
- datasets/san_francisco_trees/_images/run_csv_transform_kub/requirements.txt
- datasets/san_francisco_trees/_terraform/provider.tf
- datasets/san_francisco_trees/_terraform/san_francisco_trees_dataset.tf
- datasets/san_francisco_trees/_terraform/street_trees_pipeline.tf
- datasets/san_francisco_trees/_terraform/variables.tf
- datasets/san_francisco_trees/dataset.yaml
- datasets/san_francisco_trees/street_trees/pipeline.yaml
- datasets/san_francisco_trees/street_trees/street_trees_dag.py
> feat: Onboard San Francisco Street Trees dataset

- datasets/covid19_google_mobility/_images/run_csv_transform_kub/Dockerfile
- datasets/covid19_google_mobility/_images/run_csv_transform_kub/csv_transform.py
- datasets/covid19_google_mobility/_images/run_csv_transform_kub/requirements.txt
- datasets/covid19_google_mobility/_terraform/covid19_google_mobility_dataset.tf
- datasets/covid19_google_mobility/_terraform/mobility_report_pipeline.tf
- datasets/covid19_google_mobility/_terraform/provider.tf
- datasets/covid19_google_mobility/_terraform/variables.tf
- datasets/covid19_google_mobility/dataset.yaml
- datasets/covid19_google_mobility/mobility_report/mobility_report_dag.py
- datasets/covid19_google_mobility/mobility_report/pipeline.yaml
> feat: Onboard COVID19 Google Mobility dataset

- datasets/cms_medicare/_images/run_csv_transform_kub/Dockerfile
- datasets/cms_medicare/_images/run_csv_transform_kub/csv_transform.py
- datasets/cms_medicare/_images/run_csv_transform_kub/requirements.txt
- datasets/cms_medicare/_terraform/cms_medicare_dataset.tf
- datasets/cms_medicare/_terraform/hospital_general_info_pipeline.tf
- datasets/cms_medicare/_terraform/inpatient_charges_pipeline.tf
- datasets/cms_medicare/_terraform/outpatient_charges_pipeline.tf
- datasets/cms_medicare/_terraform/provider.tf
- datasets/cms_medicare/_terraform/variables.tf
- datasets/cms_medicare/dataset.yaml
- datasets/cms_medicare/hospital_general_info/hospital_general_info_dag.py
- datasets/cms_medicare/hospital_general_info/pipeline.yaml
- datasets/cms_medicare/inpatient_charges/inpatient_charges_dag.py
- datasets/cms_medicare/inpatient_charges/pipeline.yaml
- datasets/cms_medicare/outpatient_charges/outpatient_charges_dag.py
- datasets/cms_medicare/outpatient_charges/pipeline.yaml
> feat: Onboard CMS Medicare

- datasets/austin_waste/_terraform/waste_and_diversion_pipeline.tf
- datasets/bls/_terraform/c_cpi_u_pipeline.tf
- datasets/bls/_terraform/cpi_u_pipeline.tf
- datasets/bls/_terraform/employment_hours_earnings_pipeline.tf
- datasets/bls/_terraform/employment_hours_earnings_series_pipeline.tf
- datasets/bls/_terraform/unemployment_cps_pipeline.tf
- datasets/bls/_terraform/unemployment_cps_series_pipeline.tf
- datasets/bls/_terraform/wm_pipeline.tf
- datasets/bls/_terraform/wm_series_pipeline.tf
- datasets/chicago_crime/_terraform/crime_pipeline.tf
- datasets/world_bank_intl_education/_terraform/country_series_definitions_pipeline.tf
- datasets/world_bank_intl_education/_terraform/country_summary_pipeline.tf
- datasets/world_bank_intl_education/_terraform/series_summary_pipeline.tf
Follow up to #203 for datasets that we missed.
> fix: Namespace Terraform resources under dataset names

- datasets/cdc_places/_images/run_csv_transform_kub/Dockerfile
- datasets/cdc_places/_images/run_csv_transform_kub/csv_transform.py
- datasets/cdc_places/_images/run_csv_transform_kub/requirements.txt
- datasets/cdc_places/_terraform/cdc_places_dataset.tf
- datasets/cdc_places/_terraform/local_data_for_better_health_county_data_pipeline.tf
- datasets/cdc_places/_terraform/provider.tf
- datasets/cdc_places/_terraform/variables.tf
- datasets/cdc_places/dataset.yaml
- datasets/cdc_places/local_data_for_better_health_county_data/local_data_for_better_health_county_data_dag.py
- datasets/cdc_places/local_data_for_better_health_county_data/pipeline.yaml
1) datasets/cdc_places.local_data_for_better_health_county_data
> feat: Onboard CDC Places Dataset

- datasets/idc/_images/generate_bq_views/queries/current/analysis_results_metadata.sql
- datasets/idc/_images/generate_bq_views/queries/current/auxiliary_metadata.sql
- datasets/idc/_images/generate_bq_views/queries/current/dicom_all.sql
- datasets/idc/_images/generate_bq_views/queries/current/dicom_metadata.sql
- datasets/idc/_images/generate_bq_views/queries/current/dicom_metadata_curated.sql
- datasets/idc/_images/generate_bq_views/queries/current/measurement_groups.sql
- datasets/idc/_images/generate_bq_views/queries/current/nlst_canc.sql
- datasets/idc/_images/generate_bq_views/queries/current/nlst_ctab.sql
- datasets/idc/_images/generate_bq_views/queries/current/nlst_ctabc.sql
- datasets/idc/_images/generate_bq_views/queries/current/nlst_prsn.sql
- datasets/idc/_images/generate_bq_views/queries/current/nlst_screen.sql
- datasets/idc/_images/generate_bq_views/queries/current/original_collections_metadata.sql
- datasets/idc/_images/generate_bq_views/queries/current/qualitative_measurements.sql
- datasets/idc/_images/generate_bq_views/queries/current/quantitative_measurements.sql
- datasets/idc/_images/generate_bq_views/queries/current/segmentations.sql
- datasets/idc/_images/generate_bq_views/queries/current/tcga_biospecimen_rel9.sql
- datasets/idc/_images/generate_bq_views/queries/current/tcga_clinical_rel9.sql
- datasets/idc/_images/generate_bq_views/queries/current/version_metadata.sql
- datasets/idc/_terraform/idc_dataset.tf
- datasets/idc/copy_tcia_data/copy_tcia_data_dag.py
- datasets/idc/copy_tcia_data/pipeline.yaml
- datasets/idc/dataset.yaml
> feat: Adds `idc_current` dataset for IDC-TCIA 

- datasets/america_health_rankings/_images/run_csv_transform_kub/Dockerfile
- datasets/america_health_rankings/_images/run_csv_transform_kub/csv_transform.py
- datasets/america_health_rankings/_images/run_csv_transform_kub/requirements.txt
- datasets/america_health_rankings/_terraform/ahr_pipeline.tf
- datasets/america_health_rankings/_terraform/america_health_rankings_dataset.tf
- datasets/america_health_rankings/_terraform/provider.tf
- datasets/america_health_rankings/_terraform/variables.tf
- datasets/america_health_rankings/ahr/ahr_dag.py
- datasets/america_health_rankings/ahr/pipeline.yaml
- datasets/america_health_rankings/dataset.yaml
1) america_health_rankings.ahr
> feat: Onboard America Health Rankings Dataset

- datasets/census_opportunity_atlas/_images/run_csv_transform_kub/Dockerfile
- datasets/census_opportunity_atlas/_images/run_csv_transform_kub/csv_transform.py
- datasets/census_opportunity_atlas/_images/run_csv_transform_kub/requirements.txt
- datasets/census_opportunity_atlas/_terraform/census_opportunity_atlas_dataset.tf
- datasets/census_opportunity_atlas/_terraform/provider.tf
- datasets/census_opportunity_atlas/_terraform/tract_covariates_pipeline.tf
- datasets/census_opportunity_atlas/_terraform/variables.tf
- datasets/census_opportunity_atlas/dataset.yaml
- datasets/census_opportunity_atlas/tract_covariates/pipeline.yaml
- datasets/census_opportunity_atlas/tract_covariates/tract_covariates_dag.py
1)census_opportunity_atlas.tract_covariates
> feat: Onboard Census Opportunity Atlas Dataset

- datasets/city_health_dashboard/_images/run_csv_transform_kub/Dockerfile
- datasets/city_health_dashboard/_images/run_csv_transform_kub/csv_transform.py
- datasets/city_health_dashboard/_images/run_csv_transform_kub/requirements.txt
- datasets/city_health_dashboard/_terraform/chdb_data_city_all_pipeline.tf
- datasets/city_health_dashboard/_terraform/chdb_data_tract_all_pipeline.tf
- datasets/city_health_dashboard/_terraform/city_health_dashboard_dataset.tf
- datasets/city_health_dashboard/_terraform/provider.tf
- datasets/city_health_dashboard/_terraform/variables.tf
- datasets/city_health_dashboard/chdb_data_city_all/chdb_data_city_all_dag.py
- datasets/city_health_dashboard/chdb_data_city_all/pipeline.yaml
- datasets/city_health_dashboard/chdb_data_tract_all/chdb_data_tract_all_dag.py
- datasets/city_health_dashboard/chdb_data_tract_all/pipeline.yaml
- datasets/city_health_dashboard/dataset.yaml
1) city_health_dashboard.chdb_data_tract_all
2) city_health_dashboard.chdb_data_city_all
> feat: Onboard City Health Dashboard Dataset

- datasets/cdc_chronic_disease_indicators/_images/run_csv_transform_kub/Dockerfile
- datasets/cdc_chronic_disease_indicators/_images/run_csv_transform_kub/csv_transform.py
- datasets/cdc_chronic_disease_indicators/_images/run_csv_transform_kub/requirements.txt
- datasets/cdc_chronic_disease_indicators/_terraform/cdc_chronic_disease_indicators_dataset.tf
- datasets/cdc_chronic_disease_indicators/_terraform/chronic_disease_indicators_pipeline.tf
- datasets/cdc_chronic_disease_indicators/_terraform/provider.tf
- datasets/cdc_chronic_disease_indicators/_terraform/variables.tf
- datasets/cdc_chronic_disease_indicators/chronic_disease_indicators/chronic_disease_indicators_dag.py
- datasets/cdc_chronic_disease_indicators/chronic_disease_indicators/pipeline.yaml
- datasets/cdc_chronic_disease_indicators/dataset.yaml
1) cdc_chronic_disease_indicators.chronic_disease_indicators
> feat: Onboard Chronic Disease Indicators Dataset

- .gitignore
- datasets/mlcommons/_terraform/mlcommons_dataset.tf
- datasets/mlcommons/_terraform/provider.tf
- datasets/mlcommons/_terraform/variables.tf
- datasets/mlcommons/dataset.yaml
- datasets/mlcommons/mswc/mswc_dag.py
- datasets/mlcommons/mswc/pipeline.yaml
In collaboration with [MLCommons](https://mlcommons.org/).
> feat: Onboard MLCommons Multilingual Spoken Words Corpus (MSWC) dataset

- datasets/news_hatecrimes/_images/run_csv_transform_kub/Dockerfile
- datasets/news_hatecrimes/_images/run_csv_transform_kub/csv_transform.py
- datasets/news_hatecrimes/_images/run_csv_transform_kub/requirements.txt
- datasets/news_hatecrimes/_terraform/hatecrimes_pipeline.tf
- datasets/news_hatecrimes/_terraform/news_hatecrimes_dataset.tf
- datasets/news_hatecrimes/_terraform/provider.tf
- datasets/news_hatecrimes/_terraform/variables.tf
- datasets/news_hatecrimes/dataset.yaml
- datasets/news_hatecrimes/hatecrimes/hatecrimes_dag.py
- datasets/news_hatecrimes/hatecrimes/pipeline.yaml
Pipelines : 
- news_hatecrimes/hatecrimes
> feat: Onboard News Hate Crimes dataset

- datasets/covid19_cds_eu/_images/run_csv_transform_kub/Dockerfile
- datasets/covid19_cds_eu/_images/run_csv_transform_kub/csv_transform.py
- datasets/covid19_cds_eu/_images/run_csv_transform_kub/requirements.txt
- datasets/covid19_cds_eu/_terraform/covid19_cds_eu_dataset.tf
- datasets/covid19_cds_eu/_terraform/global_cases_by_province_pipeline.tf
- datasets/covid19_cds_eu/_terraform/provider.tf
- datasets/covid19_cds_eu/_terraform/variables.tf
- datasets/covid19_cds_eu/dataset.yaml
- datasets/covid19_cds_eu/global_cases_by_province/global_cases_by_province_dag.py
- datasets/covid19_cds_eu/global_cases_by_province/pipeline.yaml
Pipeline included : 
- covid19_cds_eu.global_cases_by_province
> feat: Onboard COVID-19 CDS EU dataset

- datasets/eumetsat/_terraform/eumetsat_dataset.tf
- datasets/eumetsat/_terraform/provider.tf
- datasets/eumetsat/_terraform/variables.tf
- datasets/eumetsat/dataset.yaml
- datasets/eumetsat/solar_forecasting/pipeline.yaml
- datasets/eumetsat/solar_forecasting/solar_forecasting_dag.py
Data prepared by [Open Climate Fix](https://openclimatefix.org).
> feat: Onboard EUMETSAT Solar Forecasting dataset

- datasets/iowa_liquor_sales/pipelines/sales/pipeline.yaml
Change the location column from STRING to GEOGRAPHY type
> feat: Update "location" to GEOGRAPHY type for `datasets/google_trends` schema

- scripts/deploy_dag.py
- tests/scripts/test_deploy_dag.py
Local Airflow development using the architecture is underdeveloped. We'll remove stuff related to it for now and revisit this in the future.
> cleanup: Remove local Airflow development

- datasets/san_francisco_311/docs/tutorials/predict_weekly_calls/sf_311_weekly_calls_prediction_test.py
- samples/tutorial.ipynb
> Feat: Added a template for tutorials.

- poetry.lock
- pyproject.toml
> chore: Setup the switch to poetry

- datasets/san_francisco_311/docs/queries/artifact.yaml
- datasets/san_francisco_311/docs/queries/category_by_complaint_source/category_by_complaint_source.sql
> Feat: Add 311 example

- datasets/san_francisco_311/docs/queries/artifact.yaml
> fix: Delete artifact.yaml

- datasets/broad_references/infra/provider.tf
- datasets/broad_references/infra/variables.tf
- datasets/broad_references/pipelines/copy_gcs_bucket/copy_gcs_bucket_dag.py
- datasets/broad_references/pipelines/copy_gcs_bucket/pipeline.yaml
- datasets/broad_references/pipelines/dataset.yaml
Automates the syncing of data to deliver to the public `gcp-public-data--broad-references` bucket
> feat: Onboard Broad Genome References dataset

- datasets/gbif/infra/gbif_dataset.tf
- datasets/gbif/infra/gcs_to_bq_pipeline.tf
- datasets/gbif/infra/provider.tf
- datasets/gbif/infra/variables.tf
- datasets/gbif/pipelines/dataset.yaml
- datasets/gbif/pipelines/gcs_to_bq/gcs_to_bq_dag.py
- datasets/gbif/pipelines/gcs_to_bq/pipeline.yaml
Onboards the Global Biodiversity Information Facility (GBIF) dataset on  `datasets/gbif`.
> feat: Onboard GBIF dataset

- datasets/scalable_open_source/infra/provider.tf
- datasets/scalable_open_source/infra/scalable_open_source_dataset.tf
- datasets/scalable_open_source/infra/variables.tf
- datasets/scalable_open_source/pipelines/_images/bq_data_transfer/Dockerfile
- datasets/scalable_open_source/pipelines/_images/bq_data_transfer/requirements.txt
- datasets/scalable_open_source/pipelines/_images/bq_data_transfer/script.py
- datasets/scalable_open_source/pipelines/dataset.yaml
- datasets/scalable_open_source/pipelines/deps_dev/deps_dev_dag.py
- datasets/scalable_open_source/pipelines/deps_dev/pipeline.yaml
Onboards the [deps.dev](https://deps.dev/) dataset from Open Source Insights on `datasets/scalable_open_source`.
> feat: Onboard deps.dev dataset

- datasets/bls/infra/bls_dataset.tf
- datasets/bls/infra/c_cpi_u_pipeline.tf
- datasets/bls/infra/cpi_u_pipeline.tf
- datasets/bls/infra/cpsaat18_pipeline.tf
- datasets/bls/infra/employment_hours_earnings_pipeline.tf
- datasets/bls/infra/employment_hours_earnings_series_pipeline.tf
- datasets/bls/infra/unemployment_cps_pipeline.tf
- datasets/bls/infra/unemployment_cps_series_pipeline.tf
- datasets/bls/infra/variables.tf
- datasets/bls/infra/wm_pipeline.tf
- datasets/bls/infra/wm_series_pipeline.tf
- datasets/bls/pipelines/cpsaat18/cpsaat18_dag.py
- datasets/bls/pipelines/cpsaat18/pipeline.yaml
- datasets/bls/pipelines/dataset.yaml
Also revised the TF files under `datasets/bls`
> feat: Update BLS - CPSAAT18 with 2021 data

- datasets/google_dei/pipelines/diversity_annual_report/diversity_annual_report_dag.py
- datasets/google_dei/pipelines/diversity_annual_report/pipeline.yaml
Modifies a few columns in the `google_dei.region_non_intersectional_hiring` table.
> chore: Changes to Diversity Annual Report (google_dei) schema

- datasets/idc/infra/idc_dataset.tf
- datasets/idc/infra/variables.tf
- datasets/idc/pipelines/copy_tcia_data/copy_tcia_data_dag.py
- datasets/idc/pipelines/copy_tcia_data/pipeline.yaml
- datasets/idc/pipelines/dataset.yaml
Onboards IDC's v9 version of The Cancer Imaging Archive.
> feat: Onboard IDC v9 dataset

- datasets/open_targets/infra/open_targets_dataset.tf
- datasets/open_targets/pipelines/copy_genetics_data/copy_genetics_data_dag.py
- datasets/open_targets/pipelines/copy_genetics_data/pipeline.yaml
- datasets/open_targets/pipelines/copy_platform_data/copy_platform_data_dag.py
- datasets/open_targets/pipelines/copy_platform_data/pipeline.yaml
Revisions to Open Targets .tf files and pipeline schedule
> chore: Revisions to Open Targets pipelines

- datasets/google_political_ads/infra/google_political_ads_dataset.tf
- datasets/google_political_ads/infra/variables.tf
- datasets/google_political_ads/pipelines/process_csvs_and_load_to_bq/pipeline.yaml
- datasets/google_political_ads/pipelines/process_csvs_and_load_to_bq/process_csvs_and_load_to_bq_dag.py
Set `google_political_ads.process_csvs_and_load_to_bq` pipeline to run every 3 hours.
> chore: Modify google_political_ads pipeline schedule

- datasets/scalable_open_source/pipelines/_images/generate_bq_views/Dockerfile
- datasets/scalable_open_source/pipelines/_images/generate_bq_views/requirements.txt
- datasets/scalable_open_source/pipelines/_images/generate_bq_views/script.py
- datasets/scalable_open_source/pipelines/deps_dev/deps_dev_dag.py
- datasets/scalable_open_source/pipelines/deps_dev/pipeline.yaml
Also copies BQ views from the source dataset.
> feat: Adds BigQuery views to `scalable_open_source` dataset

- scripts/dag_imports.json
Adds Airflow 2 operators for Cloud SQL, Cloud Functions, and GCE
> feat: Add operators for Cloud SQL, Cloud Functions, and GCE

- templates/airflow/dag.py.jinja2
- templates/airflow/dag_context.py.jinja2
- templates/airflow/default_args.py.jinja2
- templates/airflow/license_header.py.jinja2
- templates/airflow/task.py.jinja2
- templates/terraform/backend.tf.jinja2
- templates/terraform/google_bigquery_dataset.tf.jinja2
- templates/terraform/google_bigquery_table.tf.jinja2
- templates/terraform/google_storage_bucket.tf.jinja2
- templates/terraform/license_header.tf.jinja2
- templates/terraform/provider.tf.jinja2
- templates/terraform/terraform.tfvars.jinja2
- templates/terraform/variables.tf.jinja2
> chore: Update license headers to 2022

- datasets/idc/infra/idc_dataset.tf
- datasets/idc/infra/provider.tf
- datasets/idc/infra/variables.tf
- datasets/idc/pipelines/copy_tcia_data/copy_tcia_data_dag.py
- datasets/idc/pipelines/copy_tcia_data/pipeline.yaml
- datasets/idc/pipelines/dataset.yaml
> feat: Onboard IDC v10 dataset

- datasets/google_cloud_release_notes/infra/google_cloud_release_notes_dataset.tf
- datasets/google_cloud_release_notes/infra/provider.tf
- datasets/google_cloud_release_notes/infra/release_notes_pipeline.tf
- datasets/google_cloud_release_notes/infra/variables.tf
- datasets/google_cloud_release_notes/pipelines/_images/copy_bq_dataset/Dockerfile
- datasets/google_cloud_release_notes/pipelines/_images/copy_bq_dataset/requirements.txt
- datasets/google_cloud_release_notes/pipelines/_images/copy_bq_dataset/script.py
- datasets/google_cloud_release_notes/pipelines/release_notes/pipeline.yaml
- datasets/google_cloud_release_notes/pipelines/release_notes/release_notes_dag.py
> chore: Update GCP release notes dataset to Airflow 2

- .gitignore
> chore: Ignore tfstate files and backup equivalents

- datasets/deepmind/pipelines/alphafold/alphafold_dag.py
- datasets/deepmind/pipelines/alphafold/pipeline.yaml
> fix: AlphaFold dataset - add accession_ids.csv to the bucket

- datasets/open_buildings/pipelines/open_buildings/pipeline.yaml
Fixes to issues overlooked in last PR.
> fix: Resolve variables issues in Open Buildings Dataset

- datasets/ebi_chembl/infra/chembl_30_pipeline.tf
- datasets/ebi_chembl/infra/ebi_chembl_dataset.tf
- datasets/ebi_chembl/infra/provider.tf
- datasets/ebi_chembl/infra/variables.tf
- datasets/ebi_chembl/pipelines/_images/run_csv_transform_kub/Dockerfile
- datasets/ebi_chembl/pipelines/_images/run_csv_transform_kub/csv_transform.py
- datasets/ebi_chembl/pipelines/_images/run_csv_transform_kub/requirements.txt
- datasets/ebi_chembl/pipelines/chembl_30/chembl_30_dag.py
- datasets/ebi_chembl/pipelines/chembl_30/pipeline.yaml
- datasets/ebi_chembl/pipelines/dataset.yaml
Dataset: ebi_chembl Pipeline: chembl_30
> Feat: Onboard EMBL - EBI ChEMBL dataset

- datasets/google_political_ads/infra/google_political_ads_dataset.tf
- datasets/google_political_ads/infra/process_csvs_and_load_to_bq_pipeline.tf
- datasets/google_political_ads/infra/provider.tf
- datasets/google_political_ads/infra/variables.tf
- datasets/google_political_ads/pipelines/_images/run_csv_transform_kub/csv_transform.py
- datasets/google_political_ads/pipelines/process_csvs_and_load_to_bq/pipeline.yaml
- datasets/google_political_ads/pipelines/process_csvs_and_load_to_bq/process_csvs_and_load_to_bq_dag.py
Modified `datasets/google_political_ads` to add the BRL currency column.
> fix: Adds BRL currency in Google Political Ads

- datasets/noaa_passive_bioacoustic/pipelines/noaa_passive_bioacoustic/noaa_passive_bioacoustic_dag.py
- datasets/noaa_passive_bioacoustic/pipelines/noaa_passive_bioacoustic/pipeline.yaml
Resolution of overseen variable issue.
> fix: Resolve reference to hard coded bucket in "NOAA Passive Bioacoustic" dataset.

- datasets/covid19_google_mobility/infra/covid19_google_mobility_dataset.tf
- datasets/covid19_google_mobility/infra/mobility_report_pipeline.tf
- datasets/covid19_google_mobility/infra/provider.tf
- datasets/covid19_google_mobility/infra/variables.tf
- datasets/covid19_google_mobility/pipelines/dataset.yaml
- datasets/covid19_google_mobility/pipelines/mobility_report/mobility_report_dag.py
Sunset COVID-190 Google Mobility dataset.
> chore: Updates covid19_google_mobility descriptions

- datasets/irs_990/infra/irs_990_2014_pipeline.tf
- datasets/irs_990/infra/irs_990_2015_pipeline.tf
- datasets/irs_990/infra/irs_990_2016_pipeline.tf
- datasets/irs_990/infra/irs_990_2017_pipeline.tf
- datasets/irs_990/infra/irs_990_dataset.tf
- datasets/irs_990/infra/irs_990_ein_pipeline.tf
- datasets/irs_990/infra/irs_990_ez_2014_pipeline.tf
- datasets/irs_990/infra/irs_990_ez_2015_pipeline.tf
- datasets/irs_990/infra/irs_990_ez_2017_pipeline.tf
- datasets/irs_990/infra/irs_990_pf_2014_pipeline.tf
- datasets/irs_990/infra/irs_990_pf_2015_pipeline.tf
- datasets/irs_990/infra/irs_990_pf_2016_pipeline.tf
- datasets/irs_990/infra/provider.tf
- datasets/irs_990/infra/variables.tf
- datasets/irs_990/pipelines/irs_990_ein/irs_990_ein_dag.py
- datasets/irs_990/pipelines/irs_990_ein/pipeline.yaml
Dataset: irs_990 pipeline: irs_990_ein
> feat: Onboard IRS 990 EIN dataset

- datasets/covid19_italy/infra/covid19_italy_dataset.tf
- datasets/covid19_italy/infra/data_by_province_pipeline.tf
- datasets/covid19_italy/infra/data_by_region_pipeline.tf
- datasets/covid19_italy/infra/national_trends_pipeline.tf
- datasets/covid19_italy/infra/provider.tf
- datasets/covid19_italy/infra/variables.tf
- datasets/covid19_italy/pipelines/_images/run_csv_transform_kub/csv_transform.py
- datasets/covid19_italy/pipelines/data_by_province/data_by_province_dag.py
- datasets/covid19_italy/pipelines/data_by_province/pipeline.yaml
- datasets/covid19_italy/pipelines/data_by_region/data_by_region_dag.py
- datasets/covid19_italy/pipelines/data_by_region/pipeline.yaml
- datasets/covid19_italy/pipelines/dataset.yaml
- datasets/covid19_italy/pipelines/national_trends/national_trends_dag.py
- datasets/covid19_italy/pipelines/national_trends/pipeline.yaml
This request makes changes to the existing code in the `datasets/covid19_italy` folder.
> Feat: Migrate the dataset Covid19 Italy from Xenon 

- datasets/covid19_italy/pipelines/data_by_province/data_by_province_dag.py
- datasets/covid19_italy/pipelines/data_by_province/pipeline.yaml
- datasets/covid19_italy/pipelines/data_by_region/data_by_region_dag.py
- datasets/covid19_italy/pipelines/data_by_region/pipeline.yaml
- datasets/covid19_italy/pipelines/national_trends/national_trends_dag.py
- datasets/covid19_italy/pipelines/national_trends/pipeline.yaml
resolved covid19 destination bucket hard-coded issue
> fix: For Covid 19 Italy, resolved reference to destination bucket causing failure in prod.

- datasets/covid19_italy/pipelines/data_by_province/data_by_province_dag.py
- datasets/covid19_italy/pipelines/data_by_province/pipeline.yaml
- datasets/covid19_italy/pipelines/data_by_region/data_by_region_dag.py
- datasets/covid19_italy/pipelines/data_by_region/pipeline.yaml
- datasets/covid19_italy/pipelines/national_trends/national_trends_dag.py
- datasets/covid19_italy/pipelines/national_trends/pipeline.yaml
Resolution for reference to bucket in pipeline.yaml
> Fix: For COVID-19 Italy, resolve bucket variable in pipeline.yaml

- datasets/gnomad/infra/provider.tf
- datasets/gnomad/infra/variables.tf
- datasets/gnomad/pipelines/copy_gcs_bucket/copy_gcs_bucket_dag.py
- datasets/gnomad/pipelines/copy_gcs_bucket/pipeline.yaml
gnomAD pipeline was previously set to run ad-hoc. The Broad Institute now requires us to run this more frequently. Thus I have set the DAG to run daily.
> fix: Set gnomAD pipeline to run daily

- datasets/austin/pipelines/austin/austin_dag.py
- datasets/austin/pipelines/austin/data/austin_bikeshare_trips_schema.json
- datasets/austin/pipelines/austin/pipeline.yaml
Notes:
* If you are adding or editing a dataset, please specify the dataset folder involved, e.g. `datasets/google_trends`.
* If you are an external contributor, please contact the [Google Cloud Datasets team](mailto:cloud-datasets-onboarding@google.com) for your proposed dataset or feature.
* If you are adding or editing a dataset, please do it one dataset at a time. Have all the code changes inside a single  `datasets/austin` folder.
> fix: Resolve Resource Issue In Production Version Of Austin Pipeline

- datasets/open_buildings/pipelines/open_buildings/open_buildings_dag.py
- datasets/open_buildings/pipelines/open_buildings/pipeline.yaml
Fix issue with prefix in bucket specification
> fix: Resolve variables for bucket and project in Open Buildings Dataset.

- datasets/san_francisco_311/docs/tutorials/forecast_weekly_calls/sf_311_weekly_calls_forecast.ipynb
- datasets/thelook_ecommerce/pipelines/thelook_ecommerce/pipeline.yaml
> Fix: Fixing a small typo

- datasets/chicago_taxi_trips/infra/chicago_taxi_trips_dataset.tf
- datasets/chicago_taxi_trips/infra/provider.tf
- datasets/chicago_taxi_trips/infra/taxi_trips_pipeline.tf
- datasets/chicago_taxi_trips/infra/variables.tf
- datasets/chicago_taxi_trips/pipelines/_images/run_csv_transform_kub/Dockerfile
- datasets/chicago_taxi_trips/pipelines/_images/run_csv_transform_kub/csv_transform.py
- datasets/chicago_taxi_trips/pipelines/_images/run_csv_transform_kub/requirements.txt
- datasets/chicago_taxi_trips/pipelines/dataset.yaml
- datasets/chicago_taxi_trips/pipelines/taxi_trips/pipeline.yaml
- datasets/chicago_taxi_trips/pipelines/taxi_trips/taxi_trips_dag.py
Dataset: chicago_taxi_trips pipeline: taxi_trips
> Feat: Onboard Chicago Taxi Trips dataset

- datasets/london_bicycles/infra/cycle_stations_pipeline.tf
- datasets/london_bicycles/infra/london_bicycles_dataset.tf
- datasets/london_bicycles/infra/provider.tf
- datasets/london_bicycles/infra/variables.tf
- datasets/london_bicycles/pipelines/_images/run_csv_transform_kub/Dockerfile
- datasets/london_bicycles/pipelines/_images/run_csv_transform_kub/csv_transform.py
- datasets/london_bicycles/pipelines/_images/run_csv_transform_kub/requirements.txt
- datasets/london_bicycles/pipelines/cycle_stations/cycle_stations_dag.py
- datasets/london_bicycles/pipelines/cycle_stations/pipeline.yaml
- datasets/london_bicycles/pipelines/dataset.yaml
Dataset: london_bicycles pipeline: cycle_stations
> feat: Onboard London Cycle Stations dataset

- datasets/nih_gudid/infra/nih_gudid_dataset.tf
- datasets/nih_gudid/infra/nih_gudid_pipeline.tf
- datasets/nih_gudid/infra/provider.tf
- datasets/nih_gudid/infra/variables.tf
- datasets/nih_gudid/pipelines/dataset.yaml
- datasets/nih_gudid/pipelines/nih_gudid/nih_gudid_dag.py
- datasets/nih_gudid/pipelines/nih_gudid/pipeline.yaml
Dataset: nih_gudid pipeline: nih_gudid
> feat: Onboard NIH GUDID Historic data dataset

- datasets/noaa/pipelines/_images/run_csv_transform_kub/csv_transform.py
- datasets/noaa/pipelines/noaa/data/noaa_ghcn_m_data_schema.json
- datasets/noaa/pipelines/noaa/data/noaa_ghcn_m_stations_schema.json
- datasets/noaa/pipelines/noaa/noaa_dag.py
- datasets/noaa/pipelines/noaa/pipeline.yaml
Notes:
* If you are adding or editing a dataset, please specify the dataset folder involved, e.g. `datasets/google_trends`.
* If you are an external contributor, please contact the [Google Cloud Datasets team](mailto:cloud-datasets-onboarding@google.com) for your proposed dataset or feature.
* If you are adding or editing a dataset, please do it one dataset at a time. Have all the code changes inside a single  `datasets/noaa` folder.
> Feat: Onboard GHCN_M Pipelines To NOAA Dataset

- README.md
This PR adds featured datasets to the README
> chore: Add featured datasets to the README

- datasets/geos_fp/infra/geos_fp_dataset.tf
- datasets/geos_fp/infra/provider.tf
- datasets/geos_fp/infra/variables.tf
- datasets/geos_fp/pipelines/copy_files_rolling_basis/copy_files_rolling_basis_dag.py
- datasets/geos_fp/pipelines/copy_files_rolling_basis/pipeline.yaml
- datasets/geos_fp/pipelines/dataset.yaml
Dataset: 
geos_fp
Pipelines: 
copy_files_rolling_basis
> fix: Resolve GKEPod pickup process for geos_fp dataset

- datasets/noaa/pipelines/_images/run_csv_transform_kub/csv_transform.py
Resolution pertaining to Storms database looking for further detail files in the source that do not exist.
> fix: Resolve data file does not exist in Storms database pipeline.

- datasets/idc/pipelines/copy_tcia_data/copy_tcia_data_dag.py
- datasets/idc/pipelines/copy_tcia_data/pipeline.yaml
- datasets/idc/pipelines/dataset.yaml
Implement addition of v13 datasets to IDC pipeline
> fix: Add IDC v13 datasets.

- datasets/noaa/pipelines/_images/run_csv_transform_kub/csv_transform.py
- datasets/noaa/pipelines/noaa/data/noaa_gsod_by_year_schema.json
- datasets/noaa/pipelines/noaa/noaa_dag.py
- datasets/noaa/pipelines/noaa/pipeline.yaml
Add Year 2023 to NOAA GSOD Pipelines
> Feat: Add Year 2023 To NOAA GSOD Pipelines

- datasets/eumetsat/pipelines/solar_forecasting/pipeline.yaml
- datasets/eumetsat/pipelines/solar_forecasting/solar_forecasting_dag.py
Notes:
* If you are adding or editing a dataset, please specify the dataset folder involved, e.g. `datasets/google_trends`.
* If you are an external contributor, please contact the [Google Cloud Datasets team](mailto:cloud-datasets-onboarding@google.com) for your proposed dataset or feature.
* If you are adding or editing a dataset, please do it one dataset at a time. Have all the code changes inside a single  `datasets/eumetsat` folder.
> fix: Adding v4 to eumetsat dataset

- datasets/imdb/pipelines/_images/run_csv_transform_kub/csv_transform.py
- datasets/imdb/pipelines/interfaces/interfaces_dag.py
- datasets/imdb/pipelines/interfaces/pipeline.yaml
- datasets/imdb/pipelines/reviews/reviews_dag.py
Fixes datatype, memory allocation and ephemeral storage issues in `datasets/imdb`.
> Fix: Resolved datatype error causing DAG failure.  Also adjusted memory and ephemeral storage appropriately.

- datasets/eumetsat/pipelines/solar_forecasting/pipeline.yaml
- datasets/eumetsat/pipelines/solar_forecasting/solar_forecasting_dag.py
Schedule change for EUMETSAT data pipelines
> fix: Change schedule for EUMETSAT pipeline

- datasets/google_political_ads/pipelines/_images/run_csv_transform_kub/csv_transform.py
Resolve missing source data fields pertaining to HRK int data.
> fix: Resolution to issue where Spend_HRK fields no longer exist in source file for google_political_ads data load process

- datasets/austin/pipelines/_images/run_csv_transform_kub/csv_transform.py
- datasets/austin/pipelines/austin/data/austin_bikeshare_trips_schema.json
Add bike type to the existing schema in bikeshare trips.
> Fix: Add bike type field to Austin bikeshare trips schema.

- datasets/open_targets/pipelines/copy_genetics_data/copy_genetics_data_dag.py
- datasets/open_targets/pipelines/copy_genetics_data/pipeline.yaml
- datasets/open_targets/pipelines/copy_platform_data/copy_platform_data_dag.py
- datasets/open_targets/pipelines/copy_platform_data/pipeline.yaml
As per request from client 07.17.2023
> Fix: Change schedule of open targets dataset updates to 00:01 on 1st of each month

- datasets/fda_food/pipelines/_images/run_csv_transform_kub/csv_transform.py
Dataset is `datasets/fda_food`.
> Fix: Resolve issue with ordinal positioning of output file for loading FDA food enforcement data.

- datasets/noaa/pipelines/_images/run_csv_transform_kub/csv_transform.py
- datasets/noaa/pipelines/noaa/noaa_dag.py
- datasets/noaa/pipelines/noaa/pipeline.yaml
For GSOD_BY_YEAR 402 errors were outputting to the source file and breaking the process.
> Fix: Resolved issue in GSOD_BY_YEAR where files with 402 errors

- datasets/america_health_rankings/pipelines/_images/run_csv_transform_kub/Dockerfile
- datasets/america_health_rankings/pipelines/ahr/ahr_dag.py
- datasets/america_health_rankings/pipelines/ahr/pipeline.yaml
Changes required for the migration of the `america_health_rankings.ahr` DAG to the new environment.
> fix: Migration of America Health Rankings DAG to v2-2024 environment - relevant changes

- datasets/hacker_news/pipelines/_images/run_csv_transform_kub/csv_transform.py
Bad Data in the deleted field of the source file results in DAG failure.  This fixes that issue
> fix: Resolved bad field data for field *deleted* in table full.

- datasets/bls/pipelines/_images/run_csv_transform_kub/csv_transform.py
- datasets/bls/pipelines/c_cpi_u/c_cpi_u_dag.py
- datasets/bls/pipelines/c_cpi_u/pipeline.yaml
- datasets/bls/pipelines/cpi_u/cpi_u_dag.py
- datasets/bls/pipelines/cpi_u/pipeline.yaml
- datasets/bls/pipelines/cpsaat18/cpsaat18_dag.py
- datasets/bls/pipelines/employment_hours_earnings/employment_hours_earnings_dag.py
- datasets/bls/pipelines/employment_hours_earnings/pipeline.yaml
- datasets/bls/pipelines/employment_hours_earnings_series/employment_hours_earnings_series_dag.py
- datasets/bls/pipelines/employment_hours_earnings_series/pipeline.yaml
- datasets/bls/pipelines/unemployment_cps/pipeline.yaml
- datasets/bls/pipelines/unemployment_cps/unemployment_cps_dag.py
- datasets/bls/pipelines/unemployment_cps_series/pipeline.yaml
- datasets/bls/pipelines/unemployment_cps_series/unemployment_cps_series_dag.py
- datasets/bls/pipelines/wm/pipeline.yaml
- datasets/bls/pipelines/wm/wm_dag.py
- datasets/bls/pipelines/wm_series/pipeline.yaml
- datasets/bls/pipelines/wm_series/wm_series_dag.py
- datasets/hacker_news/pipelines/_images/run_csv_transform_kub/csv_transform.py
Migration Effort to push BLS pipelines to new environment.
> Fix: Migrate bls 20241007

- datasets/london_bicycles/pipelines/london_bicycles/london_bicycles_dag.py
- datasets/london_bicycles/pipelines/london_bicycles/pipeline.yaml
Migration of the London Bicycles DAG to the new environment
Notes:
* If you are adding or editing a dataset, please do it one dataset at a time. Have all the code changes inside a single  `datasets/london_bicycles` folder.
> Fix: Migration changes for London Bicycles DAG.

- datasets/covid19_symptom_search/pipelines/covid19_symptom_search/covid19_symptom_search_dag.py
- datasets/covid19_symptom_search/pipelines/covid19_symptom_search/pipeline.yaml
Breakages occurring in dag.  This PR is to remedy that issue.
> Fix: Resolving resource outage error.

- datasets/census_opportunity_atlas/pipelines/census_opportunity_atlas/census_opportunity_atlas_dag.py
- datasets/census_opportunity_atlas/pipelines/census_opportunity_atlas/pipeline.yaml
Changes relevant to the migration of the DAG to the new environment.
> Fix: Migration of census opportunity atlas to new environment.

- datasets/fda_drug/pipelines/drug_enforcement/drug_enforcement_dag.py
- datasets/fda_drug/pipelines/drug_enforcement/pipeline.yaml
Migration changes for fda_drug_enforcement DAG
Notes:
* We have made the changes in operators resource and the name space config file to generate and deploy this dag. Have all the code changes inside a single  `datasets/fda_drug`  folder.
> Fix: Migration changes for fda_drug_enforcement DAG

- datasets/fdic/pipelines/institutions/institutions_dag.py
- datasets/fdic/pipelines/institutions/pipeline.yaml
- datasets/fdic/pipelines/locations/locations_dag.py
- datasets/fdic/pipelines/locations/pipeline.yaml
Migration for FDIC dags.
Notes:
* We have made changes for Migration of FDIC dags. Have all the code changes inside a single  `datasets/FDIC` folder.
> Fix: Migration for FDIC dags.

- datasets/google_trends/pipelines/copy_trends_data/copy_trends_data_dag.py
- datasets/google_trends/pipelines/copy_trends_data/pipeline.yaml
Migrating Google Trends to new environment.
> Fix: Migrate Google Trends to new environment.

- datasets/imdb/pipelines/interfaces/interfaces_dag.py
- datasets/imdb/pipelines/interfaces/pipeline.yaml
- datasets/imdb/pipelines/reviews/pipeline.yaml
- datasets/imdb/pipelines/reviews/reviews_dag.py
Includes interfaces and reviews datasets.
> Fix: Migrate IMDB to new environment.

- datasets/iowa_liquor_sales/pipelines/sales/pipeline.yaml
- datasets/iowa_liquor_sales/pipelines/sales/sales_dag.py
Migration of IOWA Liquor Sales DAG to the new environment.
> Fix: Migrate Iowa Liquor Sales DAG to new environment.

- datasets/fda_food/pipelines/food_enforcement/food_enforcement_dag.py
- datasets/fda_food/pipelines/food_enforcement/pipeline.yaml
- datasets/fda_food/pipelines/food_events/food_events_dag.py
- datasets/fda_food/pipelines/food_events/pipeline.yaml
Migration changes for fda_food_enforcement DAG
Notes:
We have made the changes in operators resource and the name space config file to generate and deploy this dag. Have all the code changes inside a single datasets/fda_food folder.
> Fix: Migration changes for fda_food_enforcement DAG

- datasets/scalable_open_source/pipelines/deps_dev/deps_dev_dag.py
- datasets/scalable_open_source/pipelines/deps_dev/pipeline.yaml
> Fix: Migrate Scalable Open Source DAG to new environment.

- datasets/google_political_ads/pipelines/process_csvs_and_load_to_bq/pipeline.yaml
- datasets/google_political_ads/pipelines/process_csvs_and_load_to_bq/process_csvs_and_load_to_bq_dag.py
Migration Changes for "Google Political Ads" dag
Notes:
* We have made changes to fix the migration of "Google Political Ads" dag. Have all the code changes inside a single datasets/google_political_ads folder.
> Fix: Migration Changes for Google Political Ads dag

- datasets/thelook_ecommerce/pipelines/thelook_ecommerce/pipeline.yaml
- datasets/thelook_ecommerce/pipelines/thelook_ecommerce/thelook_ecommerce_dag.py
> Fix: Migrate The Look Ecommerce DAGs

- datasets/multilingual_spoken_words_corpus/pipelines/multilingual_spoken_words_corpus/multilingual_spoken_words_corpus_dag.py
- datasets/multilingual_spoken_words_corpus/pipelines/multilingual_spoken_words_corpus/pipeline.yaml
> Fix: Migrate Multilingual Spoken Words Corpus to the new environment.

- datasets/mimic_iii/pipelines/mimic_iii/mimic_iii_dag.py
- datasets/mimic_iii/pipelines/mimic_iii/pipeline.yaml
> Fix: Migrate mimic_iii dag

- datasets/google_political_ads/pipelines/process_csvs_and_load_to_bq/pipeline.yaml
- datasets/google_political_ads/pipelines/process_csvs_and_load_to_bq/process_csvs_and_load_to_bq_dag.py
Migration Changes for "Google Political Ads" dag with single cluster configuration
Notes:
* We have made changes to fix the migration of "Google Political Ads" dag. Have all the code changes inside a single datasets/google_political_ads folder.
> Fix: Migration Changes for Google Political Ads dag with single cluster configuration

- datasets/open_buildings/pipelines/open_buildings/open_buildings_dag.py
- datasets/open_buildings/pipelines/open_buildings/pipeline.yaml
> Fix: Migrate open_buildings to new environment.

- datasets/mnist/pipelines/mnist/mnist_dag.py
- datasets/mnist/pipelines/mnist/pipeline.yaml
> Fix: Migrate MNIST Dags To New Environment.

- datasets/deepmind/pipelines/alphafold/alphafold_dag.py
- datasets/deepmind/pipelines/alphafold/pipeline.yaml
- datasets/deepmind/pipelines/alphafold_v4/alphafold_v4_dag.py
- datasets/deepmind/pipelines/alphafold_v4/pipeline.yaml
> Fix: Migrate Deepmind Alphafold Dags to new environment.

- datasets/human_variant_annotation/pipelines/clinvar/clinvar_dag.py
- datasets/human_variant_annotation/pipelines/clinvar/pipeline.yaml
- datasets/human_variant_annotation/pipelines/db_snp/db_snp_dag.py
> Fix: Migrate Human Variant Annotation to new environment.

- datasets/google_cfe/pipelines/datacenter_cfe/datacenter_cfe_dag.py
Migration Changes for Google CFE dag.
Notes:
* We have made changes to fix the migration of "Google CFE" dag. Have all the code changes inside a single datasets/google_cfe folder.
> Fix: Migration Changes for Google CFE dag

- datasets/human_variant_annotation/pipelines/_images/run_csv_transform_kub/csv_transform.py
Code changes for human_variant_annotation DAG to fix value error
Notes:
We made the code changes to consider January and December(previous) months.
This implementation will rectify the current value error associated with this DAG.
> Fix: Code changes for human_variant_annotation DAG to fix value error

- datasets/irs_990/pipelines/irs_990_2017/irs_990_2017_dag.py
- datasets/irs_990/pipelines/irs_990_2017/pipeline.yaml
fix: Updated source URL of irs_990_2017
Notes:
We have made changes to fix the source URL of "irs_990.irs_990_2017" dag. Have all the code changes inside a single datasets/irs_990 folder.
> fix: Updated source URL of irs_990_2017

- datasets/irs_990/pipelines/irs_990_ez_2017/irs_990_ez_2017_dag.py
- datasets/irs_990/pipelines/irs_990_ez_2017/pipeline.yaml
fix: Updated source URL of irs_990.irs_990_ez_2017
Notes:
We have made changes to fix the source URL of "irs_990.irs_990_ez_2017" dag. Have all the code changes inside a single datasets/irs_990 folder.
> fix: Updated source URL of irs_990.irs_990_ez_2017

- datasets/irs_990/pipelines/irs_990_ez_2016/irs_990_ez_2016_dag.py
- datasets/irs_990/pipelines/irs_990_ez_2016/pipeline.yaml
fix: Updated source URL of irs_990.irs_990_ez_2016
Notes:
We have made changes to fix the source URL of "irs_990.irs_990_ez_2016" dag. Have all the code changes inside a single datasets/irs_990 folder.
> fix: Updated source URL of irs_990.irs_990_ez_2016

- datasets/irs_990/pipelines/irs_990_pf_2016/irs_990_pf_2016_dag.py
- datasets/irs_990/pipelines/irs_990_pf_2016/pipeline.yaml
fix: Updated source URL of irs_990.irs_990_pf_2016
Notes:
We have made changes to fix the source URL of "irs_990.irs_990_pf_2016" dag. Have all the code changes inside a single datasets/irs_990 folder.
> fix: Updated source URL of irs_990.irs_990_pf_2016

- datasets/irs_990/pipelines/irs_990_ez_2015/irs_990_ez_2015_dag.py
- datasets/irs_990/pipelines/irs_990_ez_2015/pipeline.yaml
fix: Updated source URL of irs_990.irs_990_ez_2015
Notes:
We have made changes to fix the source URL of "irs_990.irs_990_ez_2015" dag. Have all the code changes inside a single datasets/irs_990 folder.
> fix: Updated source URL of irs_990.irs_990_ez_2015
