datasets/covid19_tracking/covid19_tracking_dataset.tf, datasets/covid19_tracking/variables.tf, scripts/generate_terraform.py, templates/terraform/google_storage_bucket.tf.jinja2, templates/terraform/variables.tf.jinja2
_Note: This PR targets the `c19-screenshots` branch._
The name of the default env (i.e. `dev`) is being committed in GCS Terraform resources:
```hcl
resource "google_storage_bucket" "covid19_tracking-dev-processing" {
name = "${var.project_num}-covid19_tracking-dev-processing"  # the word "dev" is committed
}
output "storage_bucket-processing-name" {
value = google_storage_bucket.covid19_tracking-dev-processing.name  # the word "dev" is committed
}
```
The above should instead be
```hcl
resource "google_storage_bucket" "covid19_tracking-processing" {
name = "${var.project_num}-covid19_tracking-${var.env}-processing"  # env becomes a specified variable
}
output "storage_bucket-processing-name" {
value = google_storage_bucket.covid19_tracking-${var.env}-processing.name  # env becomes a …
```
=> Use env name as a variable for GCS Terraform resources

.github/workflows/terraform-lint.yaml, .github/workflows/unit-tests.yaml, README.md, datasets/covid19_tracking/state_screenshots/custom/web_scrape_and_generate_csv.py, datasets/covid19_tracking/state_screenshots/pipeline.yaml, datasets/covid19_tracking/state_screenshots/state_screenshots_dag.py, samples/pipeline.yaml, scripts/dag_imports.json, scripts/generate_dag.py
I occassionally get a `503 DELETE: Backend error` or `503 POST: Backend error` when moving screenshots from the Cloud Composer bucket to the final (public) destination bucket. 
I noticed that the `GoogleCloudStorageToGoogleCloudStorageOperator` does the move operation by individually copying and deleting every object. If there are tens of thousands of objects (about ~50k screenshots) to copy and delete, it's more probable to get that occassional failure.
This PR should help protect us better by decomposing the move operation into a two-step process:
1. Use `GoogleCloudStorageToGoogleCloudStorageOperator` to copy all screenshots to the destination bucket with `move_object=False` (skip the deletes).
2. Use a `GoogleCloudStorageDeleteOperator` to bulk delete all screenshots from the Cloud …
=> Minimize `503 DELETE` or `503 POST` on GCS move operation for `state_screenshots`

README.md
We'd like for the README to jump straight into the action. The "Other Requirements" section can be relocated elsewhere as part of the instructions. 
As for the authentication and authorization section, I removed those because we expect data sources to be publicly available without requiring any access policies.
=> docs: relocate "Other Requirements" README section

renovate.json
Based on #43. I removed the `matchUpdateTypes` field because the version spec already limits `apache-airflow` to `">=1.10.14,<2.0"`.
=> fix: Fix renovatebot config based on #43

README.md, datasets/ml_datasets/_terraform/ml_datasets_dataset.tf, datasets/ml_datasets/_terraform/penguins_pipeline.tf, datasets/ml_datasets/_terraform/provider.tf, datasets/ml_datasets/_terraform/variables.tf, scripts/generate_terraform.py, templates/terraform/backend.tf.jinja2, tests/scripts/test_generate_terraform.py
Based on #33. We need to optionally support Terraform remote state configuration via a `backend.tf` file that's auto-generated. It contains the following:
```hcl
terraform {
backend "gcs" {
bucket = "REMOTE_STATE_BUCKET"
prefix = "REMOTE_STATE_PREFIX"
}
}
```
This allows users to store a file on GCS representing a record of the GCP resources that Terraform keeps track of for their pipelines.
It's now possible to do this via the `--tf-state-bucket` and `--tf-state-prefix` arguments for `scripts/generate_terraform.py`.
Because backend states differ per user per environment, we only create the `backend.tf` file in the env folder specified, e.g. `.dev/datasets/ml_datasets/_terraform/backend.tf`. That is, we don't check in Terraform remote state files in the repo to keep it optional for …
=> feat: Support Terraform remote state when generating GCP resources

README.md, scripts/deploy_dag.py, tests/scripts/test_deploy_dag.py
Based on #14. Makes the `—pipeline` parameter on `scripts/deploy_dag.py` work as expected.
=> feat: Support deploying a single pipeline in a dataset

samples/pipeline.yaml, scripts/dag_imports.json, scripts/generate_dag.py
Some upcoming datasets are directly fetched from another BQ table with no transforms or schema changes needed. This PR add support for the `BigQueryToBigQueryOperator`.
=> feat: Support BigQueryToBigQueryOperator

tests/scripts/test_generate_terraform.py
Use regex matching in tests that expect the description field to be present in Terraform definitions for BQ datasets and tables. This is better than simply finding a `description` string because other Terraform resources might also have the `description` property and can result in false positive tests in the future.
=> refactor: Improve tests for BQ dataset and table descriptions

datasets/covid19_tracking/_terraform/covid19_tracking_dataset.tf, datasets/covid19_tracking/dataset.yaml, datasets/ml_datasets/dataset.yaml
Because #61 allows BQ dataset descriptions to now be generated. I reran and revised the BQ dataset descriptions for `covid19_tracking` and `ml_datasets`.
=> fix: Fix BigQuery dataset descriptions for `covid19_tracking` and `ml_datasets` 

README.md, scripts/deploy_dag.py, tests/scripts/test_deploy_dag.py
Fixes #16, where some datasets don’t need custom variables to be onboarded.
=> fix: Allow DAG deploys without `variables.json`

templates/terraform/google_bigquery_dataset.tf.jinja2, templates/terraform/google_bigquery_table.tf.jinja2, tests/scripts/test_generate_terraform.py
As per an internal Friction Friday session where newlines in BQ datasets and descriptions resulted in Terraform complaining about the format. 
The `tojson` method in jinja templates preserves escaped characters such as newlines and quotes.
=> fix: Allow newline and quotes for BQ dataset and table descriptions

datasets/bls/_terraform/bls_dataset.tf, datasets/bls/_terraform/cpsaat18_pipeline.tf, datasets/bls/_terraform/provider.tf, datasets/bls/_terraform/variables.tf, datasets/bls/cpsaat18/cpsaat18_dag.py, datasets/bls/cpsaat18/pipeline.yaml, datasets/bls/dataset.yaml
As requested by some teams to be able to join hiring data with labour statistics.
https://www.bls.gov/cps/cpsaat18.htm
=> feat: Onboard BLS - CPSAAT 2020 dataset

samples/pipeline.yaml
Helps prevent an issue where containerized tasks keep using old images despite new image versions already available.
=> docs: Add image_pull_policy for kpod operator sample

datasets/google_trends/_terraform/top_terms_pipeline.tf, datasets/google_trends/top_terms/pipeline.yaml
As requested by the Trends team. Note that this is based out of (and targets) the `partitioned-bq-tables` branch which requires that feature.
=> cleanup: Partition Google Trends tables

datasets/google_trends/_terraform/top_terms_pipeline.tf, datasets/google_trends/top_terms/pipeline.yaml, samples/pipeline.yaml, templates/terraform/google_bigquery_table.tf.jinja2, tests/scripts/test_generate_terraform.py
=> feat: Support partitioning, clustering, and protection properties for BQ tables

README.md, scripts/deploy_dag.py, scripts/generate_dag.py, tests/scripts/test_deploy_dag.py, tests/scripts/test_generate_dag.py
=> feat: Use a single file for shared Airflow variables

datasets/usa_names/usa_1910_current/pipeline.yaml, datasets/usa_names/usa_1910_current/usa_1910_current_dag.py
This PR is the **first** of a series of pull requests that upgrades the architecture to Airflow 2:
- First, merge this PR
- Then, merge #135
- And finally, merge #134 which targets the main branch
Upgrade the `usa_names` pipeline to use Airflow 2 provider operators.
=> feat: Upgrade `usa_names` pipeline to use Airflow 2 operators

Pipfile, Pipfile.lock, README.md, datasets/usa_names/usa_1910_current/pipeline.yaml, datasets/usa_names/usa_1910_current/usa_1910_current_dag.py, requirements-dev.txt, scripts/deploy_dag.py, scripts/generate_dag.py
This PR is the **second** of a series of breaking pull requests that upgrades the architecture to Airflow 2: 
- First, merge #136
- Then merge this PR
- And finally, merge #134 which targets the main branch
Update the dependencies to install Airflow 2.
=> feat!: Upgrade dependencies to Airflow 2.1.1

Pipfile, Pipfile.lock, README.md, datasets/bls/cpsaat18/pipeline.yaml, datasets/covid19_tracking/city_level_cases_and_deaths/pipeline.yaml, datasets/covid19_tracking/covid_racial_data_tracker/pipeline.yaml, datasets/covid19_tracking/national_testing_and_outcomes/pipeline.yaml, datasets/covid19_tracking/state_facility_level_long_term_care/pipeline.yaml, datasets/covid19_tracking/state_level_aggregate_long_term_care/pipeline.yaml, datasets/covid19_tracking/state_level_cumulative_long_term_care/pipeline.yaml, datasets/covid19_tracking/state_level_current_outbreak_long_term_care/pipeline.yaml, datasets/covid19_tracking/state_screenshots/pipeline.yaml, datasets/covid19_tracking/state_testing_and_outcomes/pipeline.yaml, datasets/covid19_vaccination_access/vaccination_access_to_bq/pipeline.yaml, datasets/covid19_vaccination_search_insights/covid19_vaccination_search_insights/pipeline.yaml, datasets/google_dei/diversity_annual_report/pipeline.yaml, datasets/google_trends/top_terms/pipeline.yaml, datasets/iowa_liquor_sales_forecasting/2020_sales_train/pipeline.yaml, datasets/iowa_liquor_sales_forecasting/2021_sales_predict/pipeline.yaml, datasets/ml_datasets/penguins/pipeline.yaml, datasets/usa_names/usa_1910_current/pipeline.yaml, datasets/usa_names/usa_1910_current/usa_1910_current_dag.py, datasets/vizgen_merfish/mouse_brain_map/pipeline.yaml, requirements-dev.txt, samples/pipeline.yaml, scripts/dag_imports.json, scripts/deploy_dag.py, scripts/generate_dag.py, tests/scripts/test_deploy_dag.py, tests/scripts/test_generate_dag.py
This PR is the **last** to be merged in a series of breaking pull requests that upgrades the architecture to Airflow 2:
- First, merge #136
- Then, merge #135
- Then, merge #138 
- And finally this PR, which targets the main branch
First, DAGs are now generated using Airflow 2.0+ operators by specifying an `airflow_version: 2` in the `dag` block of the YAML config
```yaml
dag:
airflow_version: 2
```
For backwards compatibility, pipelines default to using Airflow 1.10 operators if `airflow_version` is unspecified (tested it with the `usa_names` dataset in #136.
Next, we can now import Airflow 2.x equivalents of commonly used Airflow 1.10.15 operators.
Next, because Airflow 1.10 DAGs can run in an Airflow 2.x environment, but not the other way around, I added some version compatibility …
=> feat!: Adds support for Airflow 2 Cloud Composer environment and operators

datasets/noaa/_images/run_csv_transform_kub_gsod_stations/Dockerfile, datasets/noaa/_images/run_csv_transform_kub_gsod_stations/Pipfile, datasets/noaa/_images/run_csv_transform_kub_gsod_stations/csv_transform.py, datasets/noaa/_images/run_csv_transform_kub_gsod_stations/requirements.txt, datasets/noaa/_images/run_csv_transform_kub_lightning_strikes_by_year/Dockerfile, datasets/noaa/_images/run_csv_transform_kub_lightning_strikes_by_year/Pipfile, datasets/noaa/_images/run_csv_transform_kub_lightning_strikes_by_year/csv_transform.py, datasets/noaa/_images/run_csv_transform_kub_lightning_strikes_by_year/requirements.txt, datasets/noaa/_terraform/gsod_stations_pipeline.tf, datasets/noaa/_terraform/lightning_strikes_by_year_pipeline.tf, datasets/noaa/_terraform/noaa_dataset.tf, datasets/noaa/_terraform/provider.tf, datasets/noaa/_terraform/variables.tf, datasets/noaa/dataset.yaml, datasets/noaa/gsod_stations/gsod_stations_dag.py, datasets/noaa/gsod_stations/pipeline.yaml, datasets/noaa/lightning_strikes_by_year/lightning_strikes_by_year_dag.py, datasets/noaa/lightning_strikes_by_year/pipeline.yaml, datasets/noaa/noaa_variables.json
=> feat: Onboard NOAA dataset

datasets/geos_fp/_images/rolling_copy/script.py, datasets/geos_fp/copy_files_rolling_basis/copy_files_rolling_basis_dag.py, datasets/geos_fp/copy_files_rolling_basis/pipeline.yaml
- Temporary GCS objects generated by gsutil's parallel composite for `geos_fp` dataset. Those must be manually deleted as recommended [here](https://cloud.google.com/storage/docs/uploads-downloads#gsutil-pcu)
- Add node pool affinities for KPod operators for `geos_fp` dataset
=> fix: Delete temp GCS objects generated by gsutil's parallel composite upload for `geos_fp` dataset

.gitignore
Avoids unintentional checking in of `*.tfvars` files that contain specific values of GCP project IDs, service accounts, and Composer environments.
=> chore: Ignore *.tfvars files in datasets folder

samples/dataset.yaml
The [latest release](https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.0.0) from Terraform's Google provider changed the `location` field for GCS buckets to be required. This leads to failing unit tests for all PRs. This PR should unblock that.
=> fix: Set `location` field as required for GCS buckets

Pipfile, Pipfile.lock, samples/pipeline.yaml, scripts/dag_imports.json
This PR adds support for [this operator](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/_api/airflow/providers/google/cloud/operators/cloud_storage_transfer_service/index.html#airflow.providers.google.cloud.operators.cloud_storage_transfer_service.CloudDataTransferServiceGCSToGCSOperator).
=> feat: Support CloudDataTransferServiceGCSToGCSOperator

.gitignore, datasets/idc/_images/copy_bq_datasets/script.py
We only ignore `*_variables.json` files because they contain environment specific info as well as potentially sensitive values.
This PR sets the stage to allow upcoming supporting for BQ schemas to specified in `schema.json` files, instead of having very long schema definitions in the YAML files.
=> fix: Allow other JSON files to be checked in (such as `schema.json`)

README.md
Shared variables have been deprecated (#300). This PR revises the README to make use of built-in env variables instead of shared variables in Airflow templates.
=> docs: Use Airflow's environment variables feature over shared variables

datasets/idc/pipelines/_images/generate_bq_views/script.py
Fixes a bug for the IDC dataset where the generated BQ views should use the `bigquery-public-data` project .
=> fix: Fix generating BQ views for IDC dataset

tests/scripts/test_deploy_dag.py
=> chore: Removed unecessary pathlib param from test_deploy_dag

datasets/thelook_ecommerce/pipelines/thelook_ecommerce/pipeline.yaml, datasets/thelook_ecommerce/pipelines/thelook_ecommerce/thelook_ecommerce_dag.py
The pod is timing out due to a lack of resources. This PR increases the memory and CPU allocated to the pod that generates the data for TheLook dataset.
=> chore: Increased compute resources for TheLook pod

datasets/gbif/docs/queries/artifact.yaml, datasets/gbif/docs/queries/find_single_region_species.sql
=> Feat: Add a query to uncover species found in one region only.

.github/workflows/unit-tests.yaml, .pre-commit-config.yaml, datasets/cloud_storage_geo_index/pipelines/cloud_storage_geo_index/cloud_storage_geo_index_dag.py, datasets/cloud_storage_geo_index/pipelines/cloud_storage_geo_index/pipeline.yaml, datasets/noaa/pipelines/noaa/noaa_dag.py, datasets/noaa/pipelines/noaa/pipeline.yaml, poetry.lock, pyproject.toml
This PR upgrades Airflow to 2.2.5 and Python to 3.8.12 as required in the latest [Cloud Composer version list](https://cloud.google.com/composer/docs/concepts/versioning/composer-versions).
I've also piggy-backed a few package bumps for Airflow providers and Apache Beam, along with fixing a few DAGs that are now failing due to schedule syntax changes.
=> feat!: Upgrade to Airflow 2.2.5 and Python 3.8.12

scripts/deploy_dag.py
Makes it more informative to the user that the value of the remote variable will be used locally, when local variable is not set.
=> chore: Improved command line info when remote vars exist and no local vars

.github/workflows/unit-tests-airflow1.yaml
Fixes Airflow 1 tests using Python 3.8.13 by making the version more specific to 3.8.12 (as per `poetry.lock`)
=> fix: Use Python 3.8.12 for Airflow 1 tests

datasets/celeba/infra/provider.tf, datasets/celeba/infra/variables.tf, datasets/celeba/pipelines/celeba/celeba_dag.py, datasets/celeba/pipelines/celeba/pipeline.yaml, datasets/celeba/pipelines/dataset.yaml
=> Feat: Onboard Celeba dataset

scripts/generate_dag.py, tests/scripts/test_generate_dag.py
Adds the ability for users to build container images asynchronuously so they don't have to wait for GCR builds to finish.
=> feat: Support `--async-builds` flag for generate_dag.py

datasets/cloud_storage_geo_index/pipelines/cloud_storage_geo_index/pipeline.yaml
Removes the "too few spaces before comment" warnings in other pull requests.
=> chore: Remove indentation warning for cloud_storage_geo_index YAML

datasets/the_general_index/pipelines/the_general_index/pipeline.yaml, datasets/the_general_index/pipelines/the_general_index/the_general_index_dag.py
Name mismatch in pipeline.yaml cluster name
=> Fix: Resolve Cluster Name Mismatch In The General Index Dataset.

datasets/census_bureau_acs/pipelines/census_bureau_acs/census_bureau_acs_dag.py, datasets/census_bureau_acs/pipelines/census_bureau_acs/pipeline.yaml
Name mismatch in pipeline.yaml cluster name
=> Fix: Resolve Cluster Name Mismatch In Census Bureau ACS Dataset

datasets/thelook_ecommerce/pipelines/thelook_ecommerce/pipeline.yaml
Adding a user_geom and distribution_center column of type GEOGRAPHY to user and distribution_center tables
Dataset updated: datasets/thelook_ecommerce/pipelines/thelook_ecommerce/pipeline.yaml
=> feat: Add geom columns for thelook_ecommerce dataset

datasets/new_york/pipelines/new_york/new_york_dag.py, datasets/new_york/pipelines/new_york/pipeline.yaml
Resolution to issue pertaining to corrupted cluster happening when generating cluster name new-york.
=> Fix: Resolve Issue With Name Node Corruption In New york Dataset

datasets/census_opportunity_atlas/infra/census_opportunity_atlas_dataset.tf, datasets/census_opportunity_atlas/infra/census_opportunity_atlas_pipeline.tf, datasets/census_opportunity_atlas/infra/provider.tf, datasets/census_opportunity_atlas/infra/variables.tf, datasets/census_opportunity_atlas/pipelines/census_opportunity_atlas/census_opportunity_atlas_dag.py, datasets/census_opportunity_atlas/pipelines/census_opportunity_atlas/pipeline.yaml, datasets/census_opportunity_atlas/pipelines/dataset.yaml
This pull request introduces 2 changes:
- replace GKE cluster operator with Pod operator
- add dataset.yaml file
=> Fix: Remove GKE cluster operator for dataset Census Opportunity Atlas

datasets/fda_food/pipelines/_images/run_csv_transform_kub/csv_transform.py, datasets/fda_food/pipelines/food_enforcement/food_enforcement_dag.py, datasets/fda_food/pipelines/food_events/food_events_dag.py
=> fix: For FDA Food Enforcement, Resolve invalid source DateTime data.

datasets/cfpb_complaints/infra/cfpb_complaints_dataset.tf, datasets/cfpb_complaints/infra/complaint_database_pipeline.tf, datasets/cfpb_complaints/infra/provider.tf, datasets/cfpb_complaints/infra/variables.tf, datasets/cfpb_complaints/pipelines/complaint_database/complaint_database_dag.py, datasets/cfpb_complaints/pipelines/complaint_database/pipeline.yaml
dataset: cfpb_complaints  Pipeline: complaint_database
Modified kubernetes pod resources. request_memory to "4G" and request_ephemeral_storage to "8G".
=> fix: Modified resources for complaint_database pipeline

datasets/deepmind/infra/deepmind_dataset.tf, datasets/deepmind/pipelines/alphafold_v4/alphafold_v4_dag.py, datasets/deepmind/pipelines/alphafold_v4/pipeline.yaml, datasets/deepmind/pipelines/dataset.yaml, poetry.lock
New `deepmind/pipelines/alphafold_v4` DAG for the next version of the dataset.
=> feat: Launch AFDB v4 dataset

datasets/idc/infra/idc_dataset.tf, datasets/idc/pipelines/copy_tcia_data/copy_tcia_data_dag.py, datasets/idc/pipelines/copy_tcia_data/pipeline.yaml, datasets/idc/pipelines/dataset.yaml
Adds the `idc_v12` and `idc_v12_clinicals` datasets and their respective objects in the GCS bucket.
=> feat: IDC v12 release

datasets/open_targets/pipelines/_images/copy_bq_datasets/script.py
The `open_targets_*` datasets haven't been updated since launch. There was a misconfiguration on the BQ copy dataset operator where the overwrite option was set to `False`, thus not updating the public datasets. This PR fixes that.
=> fix: Overwrite destination table for open_targets BQ copy operation

datasets/eumetsat/pipelines/solar_forecasting/pipeline.yaml, datasets/eumetsat/pipelines/solar_forecasting/solar_forecasting_dag.py
The addition of v4 requires splitting the dag into 2 pipelines due to inconsistency between source folder structures.
=> fix: Split dag EUMETSAT into v3 and v4 pipelines.

datasets/google_cloud_release_notes/pipelines/release_notes/pipeline.yaml, datasets/google_cloud_release_notes/pipelines/release_notes/release_notes_dag.py
Migration Changes for "Google Cloud Release Notes" dag
Notes:
* We have made changes to fix the migration of "Google Cloud Release Notes" dag. Have all the code changes inside a single  `datasets/google_cloud_release_notes` folder.
=> Fix: Migration Changes for Google Cloud Release Notes dag

datasets/libraries_io/pipelines/dependencies/dependencies_dag.py, datasets/libraries_io/pipelines/dependencies/pipeline.yaml, datasets/libraries_io/pipelines/projects/pipeline.yaml, datasets/libraries_io/pipelines/projects/projects_dag.py, datasets/libraries_io/pipelines/repositories/pipeline.yaml, datasets/libraries_io/pipelines/repositories/repositories_dag.py, datasets/libraries_io/pipelines/repository_dependencies/pipeline.yaml, datasets/libraries_io/pipelines/repository_dependencies/repository_dependencies_dag.py, datasets/libraries_io/pipelines/tags/pipeline.yaml, datasets/libraries_io/pipelines/tags/tags_dag.py, datasets/libraries_io/pipelines/versions/pipeline.yaml, datasets/libraries_io/pipelines/versions/versions_dag.py
Includes:
projects
repositories
repository_dependencies
tags
versions
=> Fix: Migrate Libraries IO DAGs to new environment.

datasets/google_political_ads/pipelines/_images/run_csv_transform_kub/csv_transform.py, datasets/google_political_ads/pipelines/process_csvs_and_load_to_bq/pipeline.yaml, datasets/google_political_ads/pipelines/process_csvs_and_load_to_bq/process_csvs_and_load_to_bq_dag.py
Made the changes to fix schema alignment for google_political_ads
Notes:
This change will align and establish the correct schema for Google political advertising datasets.
=> Fix: Made the changes to fix schema alignment for google_political_ads

datasets/bls/pipelines/cpsaat18/cpsaat18_dag.py, datasets/bls/pipelines/cpsaat18/pipeline.yaml
Made the changes to update bq bls datasets for cpsaat18 tables of the DAG bls.cpsaat18
Notes:
The source file "2023.csv" was used to update the BLS datasets for cpsaat18; the necessary code changes have been implemented.
This implementation will update the bq bls datasets with data from the latest available year.
=> Fix: Made the changes to update bq bls datasets for cpsaat18 tables
